import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import * as api from "@/lib/api";
import Providers from "@/config/providers";
import SiteHeader from "@/components/site-header";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profile = await api.getProfile();
  const categories = await api.getAllCategories();

  return (
    <html lang="ko">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SiteHeader
            profile={profile.data}
            categories={categories.data ?? []}
          />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
